### PR TITLE
Added Deimos nodes according to warframe-items

### PR DESCRIPTION
**Pull request by ModelTemplate**

### CODE REVIEW

**Comment by TobiTenno** [comment]
have you observed this anywhere or just in warframe-items?

**Comment by ModelTemplate** [comment]
Just from warframe-items.

**Comment by TobiTenno** [comment]
My worry is that warframe-items hasn't been regenerating properly.... i may end up going in and namespacing everything to wfcd so i can rerelease items and fix the processing.... that's a convo for another time tho.

**Pull request merged**
