### PR TITLE
lang updates

### PR DESCRIPTION
**Pull request by cagatayldzz**

### CODE REVIEW

**Comment by TobiTenno** [comment]
Why'd you swap the void to Orokin? It's Corrupted. 

It also looks like you outright removed a string, too?

**Comment by TobiTenno** [comment]
You'll also need to update the test schema to accept Orokin,. Because at present, there is, technically, no Orokin enemy mobs, and as such no attribution of a region being owned by them.

**Comment by cagatayldzz** [comment]
> Why'd you swap the void to Orokin? It's Corrupted.
> 
> It also looks like you outright removed a string, too?

`Mod Drop Chance Booster`  no such booster anymore. The resource booster sees this job.

**Comment by cagatayldzz** [comment]
> You'll also need to update the test schema to accept Orokin, if you do not revert the Void changes in SolNodes, because at present, there is, technically, no Orokin enemy mobs, and as such no attribution of a region being owned by them.


contains orokin instead of corrupted

**Comment by TobiTenno** [comment]
Then feel free to add Orokin to the corresponding schema and change Corrupted to Orokin, and update/add the 3/7 day boosters, but please don't remove the other because you don't think it won't ever show up again, because this isn't just for what we know to show, but to demonstrate accurate information.

**Comment by cagatayldzz** [comment]
> add the 3/7 day boosters

which boosters?

**Comment by TobiTenno** [comment]
you have them already

**Comment by TobiTenno** [comment]
Would you mind extrapolating the names of the strings for the resource boosters and add the 30day boosters?

**Comment by TobiTenno** [comment]
nvm, I can add it later if i remember, after daily reset.

**Pull request merged**
