### PR TITLE
Update synthTargets.json

### PR DESCRIPTION
**Pull request by cagatayldzz**

### CODE REVIEW

**Comment by TobiTenno** [comment]
Would you like those parts removed from the file? we can talk about it if you think it's an issue...

**Comment by cagatayldzz** [comment]
Would you like me to open the pull request again?

**Comment by TobiTenno** [comment]
totally up to you, just wanted to check if there was a specific issue having those in there?

**Comment by TobiTenno** [comment]
right, so i've got no issue cleaning t up, just curious as to if this causes any issues for you

**Comment by cagatayldzz** [comment]
editing only, T1, T2, T3, T4 are no longer needed

**Pull request merged**
