### PR TITLE
adding synth targets json

### PR DESCRIPTION
**Pull request by esunder**
Adding synth targets json from: https://steamcommunity.com/sharedfiles/filedetails/?id=666483447

in direct support for discord genesis: https://github.com/WFCD/genesis/issues/157

### CODE REVIEW

**Comment by TobiTenno** [comment]
@esunder looks like just the trailing spaces part is accurate from the bot, so if you could fix those,
and just still need to export it in the exports.js so that it's accessible from the module.

**Comment by esunder** [comment]
@TobiTenno remove trailing spaces and added to module

**Comment by TobiTenno** [comment]
cool! i'll merge this and get it released later, dunno when, and you can start consuming it from the api once i get routes set up

**Comment by TobiTenno** [comment]
or you can hardcode it in a resource file and add that as a command if you want to get started faster. i need to figure out some issues with settings on genesis before i can do anything else

**Comment by esunder** [comment]
Is the API a public github repo too? I am actually participating in Hacktoberfest, so I'm looking for more PRs :)

**Comment by TobiTenno** [comment]
it is indeed! https://github.com/wfcd/warframe-status

and then https://github.com/wfcd/genesis when you're ready for that part. i need to release data first so you can update the dependency.

**Comment by esunder** [comment]
@TobiTenno has this been pushed to npm? I did an 'npm install' today and it didnt look like it.

**Comment by TobiTenno** [comment]
it has, you'll have to do an @latest cause i did a minor release, so your semvar probably doesn't match

**Comment by TobiTenno** [comment]
It got automatically pulled into the api with the last update: https://api.warframestat.us/synthTargets

There's no search route for it yet, however, if you'd still like to do that.

**Comment by TobiTenno** [comment]
@esunder ^

**Pull request merged**
