### PR TITLE
Update languages.json

### PR DESCRIPTION
**Pull request by IhToN**
Added All VoidRelic Languages

### CODE REVIEW

**Comment by TobiTenno** [comment]
These all specify a specific relic, which those strings don't, from what I can tell, just a quality. I'll take another look, but that's what I'm seeing

**Comment by IhToN** [comment]
Yes, that's the truth, but I didn't know how to include the quality to the properties of the item without breaking the whole format of the JSON item.

**Comment by TobiTenno** [comment]
hmmm, probably just add it as `(Radiant)` or whatever the quality is at the end
Sorry for being slow about this, I hadn't had time to check

**Comment by TobiTenno** [comment]
okiedokie, thanks. dunno what we need them for, tbh.

**Comment by IhToN** [comment]
Not really necessary itself, but should be useful to find the itemTextures in the Manifests .json

https://github.com/ihton/warframe-item-data

**Comment by TobiTenno** [comment]
We don't use data mines from the game files. If that's where you got this, I'll have to turn down your pr

**Comment by IhToN** [comment]
No, all have been read and mapped from the public API. Check the python file on the repo linked.

**Comment by TobiTenno** [comment]
Looking at it, it's using mobile export... Until I hear otherwise, I guess we'll keep it

**Pull request merged**
